import Link from "next/link";

const team = [
  {
    name: "Salik Yousuf Shigan",
    role: "Builder",
    desc: "Co-built Percept as part of the CSE final year project at IUST Kashmir.",
    initials: "SY",
    color: "bg-blue-500/10 border-blue-500/20 text-blue-400",
  },
  {
    name: "Muizza Muayqeeb Akram",
    role: "Builder",
    desc: "Co-built Percept as part of the CSE final year project at IUST Kashmir.",
    initials: "MM",
    color: "bg-violet-500/10 border-violet-500/20 text-violet-400",
  },
  {
    name: "Shakeeb Arslan Naqash",
    role: "Builder",
    desc: "Co-built Percept as part of the CSE final year project at IUST Kashmir.",
    initials: "SA",
    color: "bg-teal-500/10 border-teal-500/20 text-teal-400",
  },
];

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-[#020817] text-white">
      {/* Header */}
      <section className="max-w-4xl mx-auto px-8 pt-32 pb-16">
        <div className="inline-flex items-center gap-2 bg-teal-500/10 border border-teal-500/20 rounded-full px-4 py-1.5 text-xs text-teal-300 mb-6">
          <span className="w-1.5 h-1.5 rounded-full bg-teal-400 inline-block" />
          IUST CSE · Batch 2023-27
        </div>
        <h1 className="text-4xl font-semibold mb-4">About Percept</h1>
        <p className="text-white/40 text-lg leading-relaxed max-w-2xl">
          Percept is a final year project by three CSE students at the Islamic
          University of Science and Technology, Kashmir. It combines
          neuroscience, computer vision, and AI to help educators build more
          cognitively effective presentations.
        </p>
      </section>

      {/* What we built */}
      <section className="max-w-4xl mx-auto px-8 pb-16 border-t border-white/[0.06] pt-14">
        <p className="text-xs text-white/30 uppercase tracking-widest mb-4">
          The project
        </p>
        <h2 className="text-2xl font-semibold mb-6">What is Percept?</h2>
        <div className="grid grid-cols-2 gap-6">
          <p className="text-white/50 text-sm leading-relaxed">
            Most presentation tools tell you nothing about whether your slides
            actually work. Percept fixes that by running each slide through a
            neural encoding model trained on fMRI brain data — predicting how
            the human brain responds to what it sees.
          </p>
          <p className="text-white/50 text-sm leading-relaxed">
            The result is three cognitive scores per slide — attention,
            comprehension, and cognitive load — paired with a Grad-CAM heatmap
            showing exactly where the brain focuses, and plain-language advice
            generated by an LLM to help you improve.
          </p>
        </div>
      </section>

      {/* Tech stack */}
      <section className="max-w-4xl mx-auto px-8 pb-16 border-t border-white/[0.06] pt-14">
        <p className="text-xs text-white/30 uppercase tracking-widest mb-8">
          Built with
        </p>
        <div className="flex flex-wrap gap-3">
          {[
            "Next.js",
            "TypeScript",
            "Tailwind CSS",
            "shadcn/ui",
            "TRIBE v2",
            "SigLIP",
            "Grad-CAM",
            "LibreOffice",
            "Poppler",
            "Supabase",
            "Python",
            "FastAPI",
          ].map((tech) => (
            <span
              key={tech}
              className="bg-white/[0.04] border border-white/[0.08] rounded-lg px-4 py-2 text-sm text-white/60"
            >
              {tech}
            </span>
          ))}
        </div>
      </section>

      {/* Team */}
      <section className="max-w-4xl mx-auto px-8 pb-16 border-t border-white/[0.06] pt-14">
        <p className="text-xs text-white/30 uppercase tracking-widest mb-8">
          The team
        </p>
        <div className="grid grid-cols-3 gap-6">
          {team.map((member) => (
            <div
              key={member.name}
              className="bg-white/[0.02] border border-white/[0.07] rounded-2xl p-6 hover:border-white/[0.12] transition"
            >
              <div
                className={`w-12 h-12 rounded-xl border flex items-center justify-center text-sm font-medium mb-4 ${member.color}`}
              >
                {member.initials}
              </div>
              <p className="text-sm font-medium text-white mb-1">
                {member.name}
              </p>
              <p className="text-xs text-white/40 mb-3">{member.role}</p>
              <p className="text-xs text-white/30 leading-relaxed">
                {member.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Supervisor */}
      <section className="max-w-4xl mx-auto px-8 pb-16 border-t border-white/[0.06] pt-14">
        <p className="text-xs text-white/30 uppercase tracking-widest mb-8">
          Supervised by
        </p>
        <div className="flex items-center gap-5 bg-white/[0.02] border border-white/[0.07] rounded-2xl p-6 max-w-sm">
          <div className="w-12 h-12 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-sm font-medium text-amber-400">
            SS
          </div>
          <div>
            <p className="text-sm font-medium text-white">Dr. Sahil Sholla</p>
            <p className="text-xs text-white/40 mt-0.5">
              Department of Computer Science
            </p>
            <p className="text-xs text-white/30">IUST, Kashmir</p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-4xl mx-auto px-8 pb-32">
        <div className="relative rounded-3xl border border-violet-500/20 bg-violet-500/[0.04] p-10 text-center overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-violet-600/10 via-transparent to-blue-600/10 pointer-events-none" />
          <h3 className="text-2xl font-semibold mb-3">Try it yourself</h3>
          <p className="text-white/40 text-sm mb-6">
            Upload a presentation and see how your slides perform in the brain.
          </p>
          <Link
            href="/upload"
            className="inline-block bg-blue-500 hover:bg-blue-600 transition text-white px-8 py-3 rounded-xl text-sm font-medium"
          >
            Upload a slide
          </Link>
        </div>
      </section>
    </main>
  );
}
